name: CIFuzz

on:
  pull_request:

permissions:
  contents: read

jobs:
  Fuzzing:
    runs-on: ubuntu-24.04
    steps:
      - name: Build fuzzers from this repository PR revision
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: false
          language: c++
          keep-unaffected-fuzz-targets: true

      - name: Run fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 300
          dry-run: false
          language: c++
          mode: code-change

      - name: Upload crash artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        if: failure() && steps.build.outcome == 'success'
        with:
          name: artifacts
          path: ./out/artifacts
